export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS';
export const SET_PROJECT = 'SET_PROJECT';
export const SET_PERMISSION = 'SET_PERMISSION';
